version: '3.7'
services:
  proxy:
    image: nginx:alpine
    ports:
      - "5009:5009"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - platoserver
      - platoui
  platoserver:
    build: ./platoserver
    ports:
      - "3009:3009"
    volumes:
      - type: bind
        source: ./platoserver/static/musics
        target: /go/src/github.com/slotheroo/plato/platoserver/static/musics
  platoui:
    build: ./platoui
    ports:
      - "4009:4009"
    volumes:
      - ./platoui:/app
      - '/app/node_modules'
    tty: true
